name: Postgres Database

on: 
  push:
    branches:
      - '*'
jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: python:3.11

    services:
      postgres:
        image: postgres:10.8
      env:
        USER: ${{ secrets.DB_USER }}
        PASSWORD: ${{ secrets.DB_PASS }}
        HOST: postgres
        DATABASE: ${{ secrets.DB_DATABASE }}
        PORT: 5432

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - run: -f mock_database/seed.sql
        working-directory: ./
      - name: Unit Tests
        run: make unit-test



